allowBuilds:
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@opencode-ai/ai@0.0.0-next-17403'
  - '@opencode-ai/client@0.0.0-next-17403'
  - '@opencode-ai/plugin@0.0.0-next-17403'
  - '@opencode-ai/protocol@0.0.0-next-17403'
  - '@opencode-ai/schema@0.0.0-next-17403'
